-- local telescope = require("telescope")
-- local actions = require("telescope.actions")
--
-- telescope.setup({
-- 	defaults = {
-- 		mappings = {
-- 			i = {
-- 				["<esc>"] = actions.close,
-- 				["<C-j>"] = actions.move_selection_next,
-- 				["<C-k>"] = actions.move_selection_previous,
-- 			},
-- 		},
-- 	},
-- 	prompt_prefix = "$ ",
-- 	file_ignore_patters = {
-- 		"node_modules",
-- 		".git",
-- 	},
-- })
